"""Composer resource for the ModuleX Python SDK."""

from __future__ import annotations

from typing import Any

from modulex._base import _BaseResource
from modulex._streaming import EventSourceStream


class Composer(_BaseResource):
    """Resource for the AI-assisted workflow composer and its chat sessions."""

    async def chat(
        self,
        message: str,
        *,
        workflow_id: str | None = None,
        composer_chat_id: str | None = None,
        llm: str | None = None,
        organization_id: str | None = None,
    ) -> Any:
        """Send a message to the composer and receive an AI-generated workflow response."""
        body: dict[str, Any] = {
            k: v
            for k, v in {
                "message": message,
                "workflow_id": workflow_id,
                "composer_chat_id": composer_chat_id,
                "llm": llm,
            }.items()
            if v is not None
        }
        return await self._post("/composer/chat", json=body, organization_id=organization_id)

    async def get(
        self,
        composer_chat_id: str,
        *,
        organization_id: str | None = None,
    ) -> Any:
        """Return a composer chat session by its ID."""
        return await self._get(f"/composer/chat/{composer_chat_id}", organization_id=organization_id)

    def listen(
        self,
        composer_chat_id: str,
        run_id: str,
        *,
        organization_id: str | None = None,
    ) -> EventSourceStream:
        """Open an SSE stream to receive live events for a composer chat run."""
        return self._stream_sse(
            f"/composer/chat/{composer_chat_id}/listen/{run_id}",
            organization_id=organization_id,
        )

    async def save(
        self,
        composer_chat_id: str,
        *,
        organization_id: str | None = None,
    ) -> Any:
        """Save the current workflow state generated by a composer chat session."""
        return await self._post(
            f"/composer/chat/{composer_chat_id}/save",
            organization_id=organization_id,
        )

    async def revert(
        self,
        composer_chat_id: str,
        *,
        organization_id: str | None = None,
    ) -> Any:
        """Revert the composer chat session to its last saved workflow state."""
        return await self._post(
            f"/composer/chat/{composer_chat_id}/revert",
            organization_id=organization_id,
        )

    async def history(
        self,
        workflow_id: str,
        *,
        limit: int = 10,
        organization_id: str | None = None,
    ) -> Any:
        """Return the composer chat history associated with a workflow."""
        params: dict[str, Any] = {"limit": limit}
        return await self._get(
            f"/composer/chat/workflow/{workflow_id}/history",
            params=params,
            organization_id=organization_id,
        )

    async def delete(
        self,
        composer_chat_id: str,
        *,
        permanent: bool = False,
        organization_id: str | None = None,
    ) -> Any:
        """Delete a composer chat session, optionally removing it permanently."""
        params: dict[str, Any] = {"permanent": permanent}
        return await self._delete(
            f"/composer/chat/{composer_chat_id}",
            params=params,
            organization_id=organization_id,
        )

    async def status(
        self,
        composer_chat_id: str,
        *,
        organization_id: str | None = None,
    ) -> Any:
        """Return the current processing status of a composer chat session."""
        return await self._get(
            f"/composer/chat/{composer_chat_id}/status",
            organization_id=organization_id,
        )

    async def cancel(
        self,
        composer_chat_id: str,
        *,
        organization_id: str | None = None,
    ) -> Any:
        """Cancel an in-progress composer chat run."""
        return await self._post(
            f"/composer/chat/{composer_chat_id}/cancel",
            organization_id=organization_id,
        )
